apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests: 
     - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-424102
  artifacts:
    - image: us.gcr.io/ticketing-dev-424102/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        noCache: false
      sync: 
        manual:
          - dest: .
            src: 'src/**/*.ts'
 
  